version: '3.7'

services:
  neo4j:
    image: neo4j:5.17.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password 
      - NEO4J_apoc_export_file_enabled=true 
      - NEO4J_apoc_import_file_enabled=true 
      - NEO4J_apoc_import_file_use__neo4j__config=true 
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\\\*,gds.\\\*
      - NEO4J_PLUGINS=["apoc-extended", "graph-data-science"]
      - dbms_connector_bolt_listen__address=neo4j-db:7687
      - dbms_connector_bolt_advertised__address=neo4j-db:7687
    volumes:
      - ./volumes/neo4j/data:/data
      - ./volumes/neo4j/plugins:/plugins
